### ISSUE TITLE
Unknown custom element: <v-swagger>

### ISSUE THREAD

**Issue by gtmadev** [easylogic/v-swagger#1]
I followed the install instructions. It doesn't seem to know about "v-swagger" as an element. I can see that the nodule module is there, and I am able to import it. But when I try to use it in a vue file, I just get this error.

`[Vue warn]: Unknown custom element: <v-swagger> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by gtmadev** [comment]
UPDATE...

Instead of `Vue.use(VSwagger)` 

I tried this.. (and it does work)

`Vue.component('v-swagger', VSwagger);`

**Comment by easylogic** [comment]
hi @gtmadev  
Thanks for your report.

**Comment by easylogic** [comment]
@gtmadev   where  vue component  is loading  ?   

this library is supporting to install  when it is loaded

https://github.com/easylogic/v-swagger/blob/master/src/wrapper.js#L8

**Comment by gtmadev** [comment]
Yes, I looked at that. I was surprised to keep seeing the error. I knew that Vue.component would definitely declare it though, and that did seem to work.

`import VSwagger from 'v-swagger';`

`Vue.component('v-swagger', VSwagger);`

`new Vue({
    el: '#app',
    store,
    router,
    components: { App },
    template: '<App/>'
});`

**Comment by gtmadev** [comment]
BTW.. it's working.. however, I noticed that I cannot just pull my swagger 2.0 json directly from the existing API. Looks like I will need to parse that and conform to your spec?

**Comment by easylogic** [comment]
> Yes, I looked at that. I was surprised to keep seeing the error. I knew that Vue.component would definitely declare it though, and that did seem to work.
> 
> `import VSwagger from 'v-swagger';`
> 
> `Vue.component('v-swagger', VSwagger);`
> 
> `new Vue({ el: '#app', store, router, components: { App }, template: '<App/>' });`

ok, i understood.  i have to remake to running in Vue.use

**Comment by easylogic** [comment]
> BTW.. it's working.. however, I noticed that I cannot just pull my swagger 2.0 json directly from the existing API. Looks like I will need to parse that and confirm to your spec?

Unfortunately, it is not possible now.

 The goal was to follow the swagger's View function. json load was later on the roadmap.

Please see to https://github.com/easylogic/v-swagger/blob/master/samples/simple.api.js

**Comment by gtmadev** [comment]
> > BTW.. it's working.. however, I noticed that I cannot just pull my swagger 2.0 json directly from the existing API. Looks like I will need to parse that and confirm to your spec?
> 
> Unfortunately, it is not possible now.
> 
> The goal was to follow the swagger's View function. json load was later on the roadmap.
> 
> Please see to https://github.com/easylogic/v-swagger/blob/master/samples/simple.api.js

Got it. Thanks for clarifying.
